### ISSUE TITLE
TensorFlow error on fresh Pi 5 Bookworm installation

### ISSUE THREAD

**Issue by AndrzejTunkiel** [pddpauw/BirdPi#1]
Install on fresh Bookworm Lite on Pi 5 completes successfully, however in the log I get:

20:14:31---    detections = analyzeAudioData(audioData, args.lat, args.lon, week, sensitivity, args.overlap)
20:14:31---                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:14:31---  File "/usr/local/bin/server.py", line 297, in analyzeAudioData
20:14:31---    p = predict([sig, mdata], sensitivity)
20:14:31---        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:14:31---  File "/usr/local/bin/server.py", line 247, in predict
20:14:31---    INTERPRETER.invoke()
20:14:31---  File "BirdNET-Pi/birdnet/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 941, in invoke
20:14:31---    self._interpreter.Invoke()
20:14:31---RuntimeError: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_selectNode number 29 (FlexRFFT) failed to prepare.

**To Reproduce**
1. Install Pi 5 Bookwrm Lite on Pi 5
2. Run installation script
3. Check Logs via web interface

**Your build**
Pi 5, 8GB

**

I changed the model to BirdNET_GLOBAL_6K_V2.4_Model_FP16 in tools and now it seems to work. This should be the default I guess, it is the better model anyway.

**Comment by pddpauw** [comment]
thanks, Andrezj!

you are right indeed... this one is not working.  Had not noticed since I'm always using V2.4; will soon post a comparative field test in the original BirdNet-Pi repo confirming with some data.

I will have a look at this, but can't promise to make this one work.  In that case, I will update the Readme files for this repo.

thanks again!

**Comment by pddpauw** [comment]
adapted in the install_config.sh script
