### ISSUE TITLE
BirdPi site gives 403 Forbidden

### ISSUE THREAD

**Issue by kavwad** [pddpauw/BirdPi#4]
Hello—I've just installed BirdPi on my Pi running bookworm, and while the installation seems to have completed successfully, I'm getting `403 Forbidden` when I navigate to hostname.local.

I've seen some chatter on this repo and on [BirdNET-Pi](https://github.com/mcguirepr89/BirdNET-Pi) about similar cases, but it seemed that the latest updates to this repo fixed this issue for others.

I followed @pddpauw's breadcrumbs on [StackExchange](https://raspberrypi.stackexchange.com/questions/145337/pi5-bookworm-caddy-resulting-in-403-forbidden). The following commands are working as expected:

```
birdnetpi:~/BirdNET-Pi$ apachectl status
-bash: apachectl: command not found
```

```
birdnetpi:~/BirdNET-Pi$ getcap -r / 2>/dev/null
birdnetpi:~/BirdNET-Pi$ 
```

but `curl -v 127.0.0.1:80` gives me:
```
birdnetpi:~/BirdNET-Pi$ curl -v 127.0.0.1:80
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/html
< Content-Length: 341
< Date: Tue, 02 Apr 2024 05:16:24 GMT
< Server: lighttpd/1.4.69
< 
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>403 Forbidden</title>
 </head>
 <body>
  <h1>403 Forbidden</h1>
 </body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

This beginner is grateful for your help!

**Comment by pddpauw** [comment]
are you sure Caddy got installed successfully and is running...?
Your curl command shows another webserver
try: sudo statusctl caddy
if nothing, check to restart caddy

**Comment by kavwad** [comment]
Thanks for the nudge: Caddy was installed but wasn't running because another process was already listening on port 80. In my case, it was lighttpd, which Pi-hole was using as a web server for its web interface. I assigned lighttpd a new port and was able to start Caddy successfully.
